//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成，运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Reflection;
using System.Resources;

namespace Aether.Windows.Properties;

/// <summary>
/// 强类型资源类，用于查找本地化字符串。
/// 配合 XAML 的 x:Static 标记扩展使用：{x:Static props:Strings.AppTitle}
/// </summary>
[GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[DebuggerNonUserCode]
[CompilerGenerated]
public class Strings
{
    private static ResourceManager? _resourceMan;
    private static CultureInfo? _resourceCulture;

    /// <summary>
    /// 当前资源使用的 CultureInfo。LanguageService.SetLanguage 会修改此值，
    /// 使后续 ResourceManager.GetString 调用返回新语言的字符串。
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public static CultureInfo? Culture
    {
        get => _resourceCulture;
        set => _resourceCulture = value;
    }

    /// <summary>
    /// 默认 ResourceManager，按当前 Culture 加载 Aether.Windows.Properties.Strings 资源。
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public static ResourceManager ResourceManager
    {
        get
        {
            if (ReferenceEquals(_resourceMan, null))
            {
                var temp = new ResourceManager("Aether.Windows.Properties.Strings", typeof(Strings).Assembly);
                _resourceMan = temp;
            }
            return _resourceMan;
        }
    }

    /// <summary>应用名称</summary>
    public static string AppTitle => ResourceManager.GetString("AppTitle", Culture) ?? "";

    /// <summary>会话列表标题</summary>
    public static string ConversationList_Title => ResourceManager.GetString("ConversationList_Title", Culture) ?? "";

    /// <summary>新建会话按钮</summary>
    public static string ConversationList_NewConversation => ResourceManager.GetString("ConversationList_NewConversation", Culture) ?? "";

    /// <summary>会话列表空状态</summary>
    public static string ConversationList_Empty => ResourceManager.GetString("ConversationList_Empty", Culture) ?? "";

    /// <summary>删除</summary>
    public static string ConversationList_Delete => ResourceManager.GetString("ConversationList_Delete", Culture) ?? "";

    /// <summary>置顶</summary>
    public static string ConversationList_Pin => ResourceManager.GetString("ConversationList_Pin", Culture) ?? "";

    /// <summary>取消置顶</summary>
    public static string ConversationList_Unpin => ResourceManager.GetString("ConversationList_Unpin", Culture) ?? "";

    /// <summary>搜索会话</summary>
    public static string ConversationList_Search => ResourceManager.GetString("ConversationList_Search", Culture) ?? "";

    /// <summary>发送按钮</summary>
    public static string Chat_SendMessage => ResourceManager.GetString("Chat_SendMessage", Culture) ?? "";

    /// <summary>输入框占位文本</summary>
    public static string Chat_InputPlaceholder => ResourceManager.GetString("Chat_InputPlaceholder", Culture) ?? "";

    /// <summary>思考中文案（TypingIndicator）</summary>
    public static string Chat_Thinking => ResourceManager.GetString("Chat_Thinking", Culture) ?? "";

    /// <summary>复制</summary>
    public static string Chat_Copy => ResourceManager.GetString("Chat_Copy", Culture) ?? "";

    /// <summary>重发</summary>
    public static string Chat_Retry => ResourceManager.GetString("Chat_Retry", Culture) ?? "";

    /// <summary>删除消息</summary>
    public static string Chat_DeleteMessage => ResourceManager.GetString("Chat_DeleteMessage", Culture) ?? "";

    /// <summary>设置页标题</summary>
    public static string Settings_Title => ResourceManager.GetString("Settings_Title", Culture) ?? "";

    /// <summary>BFF 地址</summary>
    public static string Settings_BffUrl => ResourceManager.GetString("Settings_BffUrl", Culture) ?? "";

    /// <summary>BFF Token</summary>
    public static string Settings_BffToken => ResourceManager.GetString("Settings_BffToken", Culture) ?? "";

    /// <summary>默认模型</summary>
    public static string Settings_DefaultModel => ResourceManager.GetString("Settings_DefaultModel", Culture) ?? "";

    /// <summary>显示 Token</summary>
    public static string Settings_ShowToken => ResourceManager.GetString("Settings_ShowToken", Culture) ?? "";

    /// <summary>隐藏 Token</summary>
    public static string Settings_HideToken => ResourceManager.GetString("Settings_HideToken", Culture) ?? "";

    /// <summary>保存按钮</summary>
    public static string Settings_Save => ResourceManager.GetString("Settings_Save", Culture) ?? "";

    /// <summary>返回按钮</summary>
    public static string Settings_Back => ResourceManager.GetString("Settings_Back", Culture) ?? "";

    /// <summary>外观</summary>
    public static string Settings_Appearance => ResourceManager.GetString("Settings_Appearance", Culture) ?? "";

    /// <summary>主题色</summary>
    public static string Settings_AccentColor => ResourceManager.GetString("Settings_AccentColor", Culture) ?? "";

    /// <summary>以太紫主题色名称</summary>
    public static string Settings_AccentColorPurple => ResourceManager.GetString("Settings_AccentColorPurple", Culture) ?? "";

    /// <summary>电气蓝主题色名称</summary>
    public static string Settings_AccentColorBlue => ResourceManager.GetString("Settings_AccentColorBlue", Culture) ?? "";

    /// <summary>星云辉主题色名称</summary>
    public static string Settings_AccentColorGlow => ResourceManager.GetString("Settings_AccentColorGlow", Culture) ?? "";

    /// <summary>语言设置项</summary>
    public static string Settings_Language => ResourceManager.GetString("Settings_Language", Culture) ?? "";

    /// <summary>Token 加密说明</summary>
    public static string Settings_TokenHint => ResourceManager.GetString("Settings_TokenHint", Culture) ?? "";

    /// <summary>简体中文（语言名称，自描述）</summary>
    public static string Settings_LanguageZhHans => ResourceManager.GetString("Settings_LanguageZhHans", Culture) ?? "";

    /// <summary>English（语言名称，自描述）</summary>
    public static string Settings_LanguageEn => ResourceManager.GetString("Settings_LanguageEn", Culture) ?? "";

    /// <summary>日本語（语言名称，自描述）</summary>
    public static string Settings_LanguageJa => ResourceManager.GetString("Settings_LanguageJa", Culture) ?? "";

    /// <summary>한국어（语言名称，自描述）</summary>
    public static string Settings_LanguageKo => ResourceManager.GetString("Settings_LanguageKo", Culture) ?? "";

    /// <summary>Français（语言名称，自描述）</summary>
    public static string Settings_LanguageFr => ResourceManager.GetString("Settings_LanguageFr", Culture) ?? "";

    /// <summary>Deutsch（语言名称，自描述）</summary>
    public static string Settings_LanguageDe => ResourceManager.GetString("Settings_LanguageDe", Culture) ?? "";

    /// <summary>Español（语言名称，自描述）</summary>
    public static string Settings_LanguageEs => ResourceManager.GetString("Settings_LanguageEs", Culture) ?? "";

    /// <summary>繁體中文（语言名称，自描述）</summary>
    public static string Settings_LanguageZhHant => ResourceManager.GetString("Settings_LanguageZhHant", Culture) ?? "";

    /// <summary>知识库标题</summary>
    public static string KnowledgeBase_Title => ResourceManager.GetString("KnowledgeBase_Title", Culture) ?? "";

    /// <summary>知识库搜索按钮</summary>
    public static string KnowledgeBase_Search => ResourceManager.GetString("KnowledgeBase_Search", Culture) ?? "";

    /// <summary>知识库搜索框占位文本</summary>
    public static string KnowledgeBase_SearchPlaceholder => ResourceManager.GetString("KnowledgeBase_SearchPlaceholder", Culture) ?? "";

    /// <summary>知识库无结果</summary>
    public static string KnowledgeBase_NoResults => ResourceManager.GetString("KnowledgeBase_NoResults", Culture) ?? "";

    /// <summary>知识库空状态</summary>
    public static string KnowledgeBase_Empty => ResourceManager.GetString("KnowledgeBase_Empty", Culture) ?? "";

    /// <summary>健康洞察标题</summary>
    public static string Health_Title => ResourceManager.GetString("Health_Title", Culture) ?? "";

    /// <summary>步数标签</summary>
    public static string Health_Steps => ResourceManager.GetString("Health_Steps", Culture) ?? "";

    /// <summary>睡眠时长标签</summary>
    public static string Health_SleepHours => ResourceManager.GetString("Health_SleepHours", Culture) ?? "";

    /// <summary>静息心率标签</summary>
    public static string Health_RestingHeartRate => ResourceManager.GetString("Health_RestingHeartRate", Culture) ?? "";

    /// <summary>上传今日健康数据按钮</summary>
    public static string Health_Upload => ResourceManager.GetString("Health_Upload", Culture) ?? "";

    /// <summary>小时单位</summary>
    public static string Health_Hours => ResourceManager.GetString("Health_Hours", Culture) ?? "";

    /// <summary>bpm 单位</summary>
    public static string Health_Bpm => ResourceManager.GetString("Health_Bpm", Culture) ?? "";

    /// <summary>步单位</summary>
    public static string Health_StepsUnit => ResourceManager.GetString("Health_StepsUnit", Culture) ?? "";

    /// <summary>加载中通用文案</summary>
    public static string Common_Loading => ResourceManager.GetString("Common_Loading", Culture) ?? "";

    /// <summary>错误通用文案</summary>
    public static string Common_Error => ResourceManager.GetString("Common_Error", Culture) ?? "";

    /// <summary>重试通用文案</summary>
    public static string Common_Retry => ResourceManager.GetString("Common_Retry", Culture) ?? "";

    /// <summary>确认通用文案</summary>
    public static string Common_Confirm => ResourceManager.GetString("Common_Confirm", Culture) ?? "";

    /// <summary>取消通用文案</summary>
    public static string Common_Cancel => ResourceManager.GetString("Common_Cancel", Culture) ?? "";

    /// <summary>
    /// 通过 key 从 ResourceManager 获取本地化字符串。供 LanguageService.GetString 调用，
    /// 也方便调用方动态读取未在 Designer 中显式声明的 key。
    /// </summary>
    /// <param name="key">资源 key（如 "AppTitle"）</param>
    /// <returns>本地化字符串；找不到时返回空字符串。</returns>
    public static string GetString(string key) =>
        ResourceManager.GetString(key, Culture) ?? "";
}
