/* Auto-generated by cbindgen. Do not edit. */

#ifndef AETHER_CORE_FFI_H
#define AETHER_CORE_FFI_H

/* Warning: 本文件由 cbindgen 生成。 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * C 侧持有的令牌桶限流器状态。
 * 不加 `#[repr(C)]`，cbindgen 生成 opaque typedef（字段含跨 crate 类型）。
 */
typedef struct AetherRateLimiter AetherRateLimiter;

typedef struct BTreeMap_i64__AccumulatedToolCall BTreeMap_i64__AccumulatedToolCall;

/**
 * SHA-256 流式哈希器（Workers 端预留，当前无调用方）。
 */
typedef struct Sha256 Sha256;

/**
 * C 侧持有的解析器状态（跨调用累积 tool_calls）。
 */
typedef struct AetherSseState {
  struct BTreeMap_i64__AccumulatedToolCall inner;
} AetherSseState;

/**
 * C 侧持有的 SHA-256 哈希器状态（流式 update）。
 */
typedef struct AetherSha256 {
  struct Sha256 inner;
} AetherSha256;

AETHER_EXPORT struct AetherSseState *aether_sse_state_new(void);

/**
 * # Safety
 * `state` 必须由 `aether_sse_state_new` 返回，且未被释放。
 */
AETHER_EXPORT void aether_sse_state_free(struct AetherSseState *state);

/**
 * 解析单行，返回 content 的 JSON 串（`null` / `"..."`）。
 * 非 data 行 / 解析失败返回空指针。
 * # Safety
 * `line` 必须是合法 NUL 结尾 UTF-8。
 */
AETHER_EXPORT char *aether_sse_parse_chunk(const char *line);

/**
 * Workers 等价的 content 提取。
 * # Safety
 * `line` 必须是合法 NUL 结尾 UTF-8。
 */
AETHER_EXPORT char *aether_sse_extract_content(const char *line);

/**
 * 带 tool_calls 累积的解析，返回 `ParsedChunk` 的 JSON 串。
 * # Safety
 * `line` 合法 UTF-8；`state` 来自 `aether_sse_state_new`。
 */
AETHER_EXPORT char *aether_sse_parse_with_tools(const char *line, struct AetherSseState *state);

/**
 * 释放由上述函数返回的字符串。空指针安全。
 * # Safety
 * `ptr` 必须由本 crate 的返回值产生，且只能释放一次。
 */
AETHER_EXPORT void aether_free_string(char *ptr);

/**
 * 释放通用 void*（预留）。
 * # Safety
 * `ptr` 必须由本 crate 产生，且只能释放一次。
 */
AETHER_EXPORT void aether_free(void *ptr);

/**
 * f32 余弦相似度。空指针或长度不等返回 0。
 * # Safety
 * `a`/`b` 必须指向至少 `a_len`/`b_len` 个有效 f32。
 */
AETHER_EXPORT
float aether_cosine_f32(const float *a,
                        uintptr_t a_len,
                        const float *b,
                        uintptr_t b_len);

/**
 * f64 余弦相似度。空指针或长度不等返回 0。
 * # Safety
 * `a`/`b` 必须指向至少 `a_len`/`b_len` 个有效 f64。
 */
AETHER_EXPORT
double aether_cosine_f64(const double *a,
                         uintptr_t a_len,
                         const double *b,
                         uintptr_t b_len);

/**
 * top-K 检索（f32）。输入 JSON：`{"query":[...],"corpus":[[...],[...]],"k":5}`；
 * 输出 JSON：`[[index,score],...]`（降序）。失败返回空指针。
 * # Safety
 * `input` 必须是合法 NUL 结尾 UTF-8。
 */
AETHER_EXPORT char *aether_top_k_f32_json(const char *input);

/**
 * 粗略估算字符串的 token 数（与 Swift `String.estimatedTokens` 算法一致）。
 * 空指针返回 0。
 * # Safety
 * `s` 必须是合法 NUL 结尾 UTF-8。
 */
AETHER_EXPORT uintptr_t aether_estimate_tokens(const char *s);

/**
 * 对输入字符串脱敏（UUID/邮箱/URL/Token/密码字段/路径）。
 * 返回新分配的 NUL 结尾 UTF-8 字符串，调用方需用 `aether_free_string` 释放。
 * 输入空指针返回空串（非空指针，需释放）。
 * # Safety
 * `input` 必须是合法 NUL 结尾 UTF-8。
 */
AETHER_EXPORT char *aether_redact(const char *input);

/**
 * 对文档分块，返回 JSON 字符串数组 `["chunk1","chunk2",...]`。
 * `max_chars == 0` 或空文本返回 `[]`。失败返回空指针。
 * 调用方需用 `aether_free_string` 释放返回值。
 * # Safety
 * `input` 必须是合法 NUL 结尾 UTF-8。
 */
AETHER_EXPORT
char *aether_chunk_document(const char *input,
                            uintptr_t max_chars,
                            uintptr_t overlap_chars);

/**
 * 创建新的 SHA-256 哈希器。调用方负责通过 `aether_sha256_free` 释放。
 */
AETHER_EXPORT struct AetherSha256 *aether_sha256_new(void);

/**
 * 追加数据到哈希。空指针安全（no-op）。
 * # Safety
 * `state` 来自 `aether_sha256_new`；`data` 指向 `len` 个有效字节。
 */
AETHER_EXPORT
void aether_sha256_update(struct AetherSha256 *state,
                          const uint8_t *data,
                          uintptr_t len);

/**
 * 完成哈希，返回小写十六进制字符串（64 字符，NUL 结尾）。
 * 不消费 state，调用方仍需 `aether_sha256_free` 释放。
 * 返回的字符串需用 `aether_free_string` 释放。空指针 state 返回空串。
 * # Safety
 * `state` 来自 `aether_sha256_new`。
 */
AETHER_EXPORT char *aether_sha256_finalize(struct AetherSha256 *state);

/**
 * 释放 SHA-256 哈希器。空指针安全。
 * # Safety
 * `state` 来自 `aether_sha256_new`，且只能释放一次。
 */
AETHER_EXPORT void aether_sha256_free(struct AetherSha256 *state);

/**
 * 一次性计算字节数组的 SHA-256，返回小写 hex 字符串。
 * 调用方需用 `aether_free_string` 释放返回值。空指针返回空串。
 * # Safety
 * `data` 指向 `len` 个有效字节。
 */
AETHER_EXPORT char *aether_sha256_hex(const uint8_t *data, uintptr_t len);

/**
 * 创建令牌桶限流器。初始令牌数 = 容量（满桶）。
 * 调用方负责通过 `aether_rate_limiter_free` 释放。
 * - `capacity`: 桶容量（最大令牌数）
 * - `refill_rate`: 每秒补充令牌数
 * - `now_ms`: 当前 epoch 毫秒时间戳
 */
AETHER_EXPORT
struct AetherRateLimiter *aether_rate_limiter_new(double capacity,
                                                  double refill_rate,
                                                  uint64_t now_ms);

/**
 * 尝试获取 `n` 个令牌。
 * 成功返回 0，失败返回正数（距下次有足够令牌的预估等待秒数）。
 * # Safety
 * `state` 来自 `aether_rate_limiter_new`。
 */
AETHER_EXPORT
double aether_rate_limiter_acquire(struct AetherRateLimiter *state,
                                   double n,
                                   uint64_t now_ms);

/**
 * 当前可用令牌数（触发补充后）。
 * # Safety
 * `state` 来自 `aether_rate_limiter_new`。
 */
AETHER_EXPORT
double aether_rate_limiter_available(struct AetherRateLimiter *state,
                                     uint64_t now_ms);

/**
 * 重置桶到满容量。
 * # Safety
 * `state` 来自 `aether_rate_limiter_new`。
 */
AETHER_EXPORT void aether_rate_limiter_reset(struct AetherRateLimiter *state, uint64_t now_ms);

/**
 * 释放令牌桶限流器。空指针安全。
 * # Safety
 * `state` 来自 `aether_rate_limiter_new`，且只能释放一次。
 */
AETHER_EXPORT void aether_rate_limiter_free(struct AetherRateLimiter *state);

#endif  /* AETHER_CORE_FFI_H */
