/* Auto-generated by cbindgen. Do not edit. */

#ifndef AETHER_CORE_FFI_H
#define AETHER_CORE_FFI_H

/* Warning: 本文件由 cbindgen 生成。 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "stdint.h"

typedef struct BTreeMap_i64__AccumulatedToolCall BTreeMap_i64__AccumulatedToolCall;

/**
 * C 侧持有的解析器状态（跨调用累积 tool_calls）。
 */
typedef struct AetherSseState {
  struct BTreeMap_i64__AccumulatedToolCall inner;
} AetherSseState;

AETHER_EXPORT struct AetherSseState *aether_sse_state_new(void);

/**
 * # Safety
 * `state` 必须由 `aether_sse_state_new` 返回，且未被释放。
 */
AETHER_EXPORT void aether_sse_state_free(struct AetherSseState *state);

/**
 * 解析单行，返回 content 的 JSON 串（`null` / `"..."`）。
 * 非 data 行 / 解析失败返回空指针。
 * # Safety
 * `line` 必须是合法 NUL 结尾 UTF-8。
 */
AETHER_EXPORT char *aether_sse_parse_chunk(const char *line);

/**
 * Workers 等价的 content 提取。
 * # Safety
 * `line` 必须是合法 NUL 结尾 UTF-8。
 */
AETHER_EXPORT char *aether_sse_extract_content(const char *line);

/**
 * 带 tool_calls 累积的解析，返回 `ParsedChunk` 的 JSON 串。
 * # Safety
 * `line` 合法 UTF-8；`state` 来自 `aether_sse_state_new`。
 */
AETHER_EXPORT char *aether_sse_parse_with_tools(const char *line, struct AetherSseState *state);

/**
 * 释放由上述函数返回的字符串。空指针安全。
 * # Safety
 * `ptr` 必须由本 crate 的返回值产生，且只能释放一次。
 */
AETHER_EXPORT void aether_free_string(char *ptr);

/**
 * 释放通用 void*（预留）。
 * # Safety
 * `ptr` 必须由本 crate 产生，且只能释放一次。
 */
AETHER_EXPORT void aether_free(void *ptr);

#endif  /* AETHER_CORE_FFI_H */
