/* Auto-generated by cbindgen. Do not edit. */

/* AETHER_EXPORT：静态库符号默认可见，宏定义为空。
 * 动态库（cdylib）构建时可通过 -DAETHER_EXPORT=__attribute__((visibility("default"))) 覆盖。 */
#ifndef AETHER_EXPORT
#define AETHER_EXPORT
#endif

#ifndef AETHER_CORE_FFI_H
#define AETHER_CORE_FFI_H

/* Warning: 本文件由 cbindgen 生成。 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#if !defined(__wasm32__)
/**
 * C 侧持有的推理引擎。opaque（字段含跨 crate 类型）。
 */
typedef struct AetherInferenceEngine AetherInferenceEngine;
#endif

/**
 * C 侧持有的令牌桶限流器状态。
 * 不加 `#[repr(C)]`，cbindgen 生成 opaque typedef（字段含跨 crate 类型）。
 */
typedef struct AetherRateLimiter AetherRateLimiter;

#if !defined(__wasm32__)
/**
 * C 侧持有的沙箱引擎。opaque（字段含跨 crate 类型，cbindgen 生成 opaque typedef）。
 */
typedef struct AetherSandbox AetherSandbox;
#endif

#if !defined(__wasm32__)
/**
 * C 侧持有的沙箱实例。opaque。
 */
typedef struct AetherSandboxInstance AetherSandboxInstance;
#endif

#if !defined(__wasm32__)
/**
 * C 侧持有的已加载模块。opaque。
 */
typedef struct AetherSandboxModule AetherSandboxModule;
#endif

typedef struct BTreeMap_i64__AccumulatedToolCall BTreeMap_i64__AccumulatedToolCall;

#if defined(__wasm32__)
/**
 * SHA-256 流式哈希器（Workers 端预留，当前无调用方）。
 */
typedef struct Sha256 Sha256;
#endif

/**
 * C 侧持有的解析器状态（跨调用累积 tool_calls）。
 */
typedef struct AetherSseState {
  struct BTreeMap_i64__AccumulatedToolCall inner;
} AetherSseState;

/**
 * C 侧持有的 SHA-256 哈希器状态（流式 update）。
 */
typedef struct AetherSha256 {
  struct Sha256 inner;
} AetherSha256;

AETHER_EXPORT struct AetherSseState *aether_sse_state_new(void);

/**
 * # Safety
 * `state` 必须由 `aether_sse_state_new` 返回，且未被释放。
 */
AETHER_EXPORT void aether_sse_state_free(struct AetherSseState *state);

/**
 * 解析单行，返回 content 的 JSON 串（`null` / `"..."`）。
 * 非 data 行 / 解析失败返回空指针。
 * # Safety
 * `line` 必须是合法 NUL 结尾 UTF-8。
 */
AETHER_EXPORT char *aether_sse_parse_chunk(const char *line);

/**
 * Workers 等价的 content 提取。
 * # Safety
 * `line` 必须是合法 NUL 结尾 UTF-8。
 */
AETHER_EXPORT char *aether_sse_extract_content(const char *line);

/**
 * 带 tool_calls 累积的解析，返回 `ParsedChunk` 的 JSON 串。
 * # Safety
 * `line` 合法 UTF-8；`state` 来自 `aether_sse_state_new`。
 */
AETHER_EXPORT char *aether_sse_parse_with_tools(const char *line, struct AetherSseState *state);

/**
 * 释放由上述函数返回的字符串。空指针安全。
 * # Safety
 * `ptr` 必须由本 crate 的返回值产生，且只能释放一次。
 */
AETHER_EXPORT void aether_free_string(char *ptr);

/**
 * 释放通用 void*（预留）。
 * # Safety
 * `ptr` 必须由本 crate 产生，且只能释放一次。
 */
AETHER_EXPORT void aether_free(void *ptr);

/**
 * f32 余弦相似度。空指针或长度不等返回 0。
 * # Safety
 * `a`/`b` 必须指向至少 `a_len`/`b_len` 个有效 f32。
 */
AETHER_EXPORT
float aether_cosine_f32(const float *a,
                        uintptr_t a_len,
                        const float *b,
                        uintptr_t b_len);

/**
 * f64 余弦相似度。空指针或长度不等返回 0。
 * # Safety
 * `a`/`b` 必须指向至少 `a_len`/`b_len` 个有效 f64。
 */
AETHER_EXPORT
double aether_cosine_f64(const double *a,
                         uintptr_t a_len,
                         const double *b,
                         uintptr_t b_len);

/**
 * top-K 检索（f32）。输入 JSON：`{"query":[...],"corpus":[[...],[...]],"k":5}`；
 * 输出 JSON：`[[index,score],...]`（降序）。失败返回空指针。
 * # Safety
 * `input` 必须是合法 NUL 结尾 UTF-8。
 */
AETHER_EXPORT char *aether_top_k_f32_json(const char *input);

/**
 * 粗略估算字符串的 token 数（与 Swift `String.estimatedTokens` 算法一致）。
 * 空指针返回 0。
 * # Safety
 * `s` 必须是合法 NUL 结尾 UTF-8。
 */
AETHER_EXPORT uintptr_t aether_estimate_tokens(const char *s);

/**
 * 对输入字符串脱敏（UUID/邮箱/URL/Token/密码字段/路径）。
 * 返回新分配的 NUL 结尾 UTF-8 字符串，调用方需用 `aether_free_string` 释放。
 * 输入空指针返回空串（非空指针，需释放）。
 * # Safety
 * `input` 必须是合法 NUL 结尾 UTF-8。
 */
AETHER_EXPORT char *aether_redact(const char *input);

/**
 * 对文档分块，返回 JSON 字符串数组 `["chunk1","chunk2",...]`。
 * `max_chars == 0` 或空文本返回 `[]`。失败返回空指针。
 * 调用方需用 `aether_free_string` 释放返回值。
 * # Safety
 * `input` 必须是合法 NUL 结尾 UTF-8。
 */
AETHER_EXPORT
char *aether_chunk_document(const char *input,
                            uintptr_t max_chars,
                            uintptr_t overlap_chars);

/**
 * 创建新的 SHA-256 哈希器。调用方负责通过 `aether_sha256_free` 释放。
 */
AETHER_EXPORT struct AetherSha256 *aether_sha256_new(void);

/**
 * 追加数据到哈希。空指针安全（no-op）。
 * # Safety
 * `state` 来自 `aether_sha256_new`；`data` 指向 `len` 个有效字节。
 */
AETHER_EXPORT
void aether_sha256_update(struct AetherSha256 *state,
                          const uint8_t *data,
                          uintptr_t len);

/**
 * 完成哈希，返回小写十六进制字符串（64 字符，NUL 结尾）。
 * 不消费 state，调用方仍需 `aether_sha256_free` 释放。
 * 返回的字符串需用 `aether_free_string` 释放。空指针 state 返回空串。
 * # Safety
 * `state` 来自 `aether_sha256_new`。
 */
AETHER_EXPORT char *aether_sha256_finalize(struct AetherSha256 *state);

/**
 * 释放 SHA-256 哈希器。空指针安全。
 * # Safety
 * `state` 来自 `aether_sha256_new`，且只能释放一次。
 */
AETHER_EXPORT void aether_sha256_free(struct AetherSha256 *state);

/**
 * 一次性计算字节数组的 SHA-256，返回小写 hex 字符串。
 * 调用方需用 `aether_free_string` 释放返回值。空指针返回空串。
 * # Safety
 * `data` 指向 `len` 个有效字节。
 */
AETHER_EXPORT char *aether_sha256_hex(const uint8_t *data, uintptr_t len);

/**
 * 创建令牌桶限流器。初始令牌数 = 容量（满桶）。
 * 调用方负责通过 `aether_rate_limiter_free` 释放。
 * - `capacity`: 桶容量（最大令牌数）
 * - `refill_rate`: 每秒补充令牌数
 * - `now_ms`: 当前 epoch 毫秒时间戳
 */
AETHER_EXPORT
struct AetherRateLimiter *aether_rate_limiter_new(double capacity,
                                                  double refill_rate,
                                                  uint64_t now_ms);

/**
 * 尝试获取 `n` 个令牌。
 * 成功返回 0，失败返回正数（距下次有足够令牌的预估等待秒数）。
 * # Safety
 * `state` 来自 `aether_rate_limiter_new`。
 */
AETHER_EXPORT
double aether_rate_limiter_acquire(struct AetherRateLimiter *state,
                                   double n,
                                   uint64_t now_ms);

/**
 * 当前可用令牌数（触发补充后）。
 * # Safety
 * `state` 来自 `aether_rate_limiter_new`。
 */
AETHER_EXPORT
double aether_rate_limiter_available(struct AetherRateLimiter *state,
                                     uint64_t now_ms);

/**
 * 重置桶到满容量。
 * # Safety
 * `state` 来自 `aether_rate_limiter_new`。
 */
AETHER_EXPORT void aether_rate_limiter_reset(struct AetherRateLimiter *state, uint64_t now_ms);

/**
 * 释放令牌桶限流器。空指针安全。
 * # Safety
 * `state` 来自 `aether_rate_limiter_new`，且只能释放一次。
 */
AETHER_EXPORT void aether_rate_limiter_free(struct AetherRateLimiter *state);

#if !defined(__wasm32__)
/**
 * 创建沙箱引擎。Pulley 解释器（无 JIT），iOS 友好。
 *
 * - `max_fuel`: CPU 指令限额（30 秒 ≈ 30_000_000_000）
 * - `max_memory_bytes`: 线性内存上限（字节，50 MB = 52_428_800）
 *
 * 失败返回空指针。
 */
AETHER_EXPORT
struct AetherSandbox *aether_sandbox_new(uint64_t max_fuel,
                                         uintptr_t max_memory_bytes);
#endif

#if !defined(__wasm32__)
/**
 * 编译 WASM 模块（字节码）。失败返回空指针。
 * # Safety
 * `sandbox` 来自 `aether_sandbox_new`；`wasm` 指向 `wasm_len` 字节。
 */
AETHER_EXPORT
struct AetherSandboxModule *aether_sandbox_load(struct AetherSandbox *sandbox,
                                                const uint8_t *wasm,
                                                uintptr_t wasm_len);
#endif

#if !defined(__wasm32__)
/**
 * 实例化模块，返回可调用实例。失败返回空指针。
 * 初始 fuel = 创建引擎时的 max_fuel。
 * # Safety
 * `module` 来自 `aether_sandbox_load`。
 */
AETHER_EXPORT
struct AetherSandboxInstance *aether_sandbox_instantiate(struct AetherSandboxModule *module);
#endif

#if !defined(__wasm32__)
/**
 * 调用插件的 execute 函数，传入 JSON 参数，返回结果 JSON 字符串。
 * 成功：`{"ok":true,"output":"...","fuelRemaining":N,"outOfFuel":false}`
 * 失败：`{"ok":false,"error":"OutOfFuel|MissingExecute|..."}`
 * 调用方需用 `aether_free_string` 释放返回值。
 * # Safety
 * `instance` 来自 `aether_sandbox_instantiate`；`args_json` 合法 NUL 结尾 UTF-8。
 */
AETHER_EXPORT
char *aether_sandbox_call_json(struct AetherSandboxInstance *instance,
                               const char *args_json);
#endif

#if !defined(__wasm32__)
/**
 * 直接调用 execute（数值参数），返回结果。失败返回 0。
 * # Safety
 * `instance` 来自 `aether_sandbox_instantiate`。
 */
AETHER_EXPORT int32_t aether_sandbox_call_raw(struct AetherSandboxInstance *instance, int32_t arg);
#endif

#if !defined(__wasm32__)
/**
 * 剩余 fuel。
 * # Safety
 * `instance` 来自 `aether_sandbox_instantiate`。
 */
AETHER_EXPORT uint64_t aether_sandbox_fuel_remaining(struct AetherSandboxInstance *instance);
#endif

#if !defined(__wasm32__)
/**
 * 重置 fuel 到初始值。
 * # Safety
 * `instance` 来自 `aether_sandbox_instantiate`。
 */
AETHER_EXPORT void aether_sandbox_refill_fuel(struct AetherSandboxInstance *instance);
#endif

#if !defined(__wasm32__)
/**
 * 释放沙箱引擎。空指针安全。
 * # Safety
 * `sandbox` 来自 `aether_sandbox_new`，且只能释放一次。
 */
AETHER_EXPORT void aether_sandbox_free(struct AetherSandbox *sandbox);
#endif

#if !defined(__wasm32__)
/**
 * 释放已加载模块。空指针安全。
 * # Safety
 * `module` 来自 `aether_sandbox_load`，且只能释放一次。
 */
AETHER_EXPORT void aether_sandbox_module_free(struct AetherSandboxModule *module);
#endif

#if !defined(__wasm32__)
/**
 * 释放沙箱实例。空指针安全。
 * # Safety
 * `instance` 来自 `aether_sandbox_instantiate`，且只能释放一次。
 */
AETHER_EXPORT void aether_sandbox_instance_free(struct AetherSandboxInstance *instance);
#endif

#if !defined(__wasm32__)
/**
 * 创建推理引擎。返回的引擎未加载模型，需调用 `aether_inference_load_model`。
 */
AETHER_EXPORT struct AetherInferenceEngine *aether_inference_new(void);
#endif

#if !defined(__wasm32__)
/**
 * 加载本地 safetensors 模型目录。
 *
 * model_dir 应包含：config.json / tokenizer.json / model.safetensors
 *
 * 参数（JSON）：
 * ```json
 * {"temperature":0.7,"maxTokens":1024,"repeatPenalty":1.1,
 *  "repeatLastN":64,"topP":0.9,"seed":null,"eosTokenId":null}
 * ```
 * seed / eosTokenId 为 null 时使用默认（seed 随机，eosTokenId 从 config.json 读取）。
 *
 * 返回：成功 0，失败返回 1（错误信息通过 aether_inference_last_error 获取）。
 * # Safety
 * `engine` 来自 `aether_inference_new`；`model_dir` 合法 NUL 结尾 UTF-8。
 */
AETHER_EXPORT
int32_t aether_inference_load_model(struct AetherInferenceEngine *engine,
                                    const char *model_dir,
                                    const char *params_json);
#endif

#if !defined(__wasm32__)
/**
 * 流式生成文本，返回 JSON 数组（每个元素含 text 与 isEnd）。
 * 格式：`[{"text":"hello","isEnd":false},...]`
 * 调用方需用 `aether_free_string` 释放返回值。失败返回空指针。
 * # Safety
 * `engine` 来自 `aether_inference_new` 且已加载模型；`prompt` 合法 NUL 结尾 UTF-8。
 */
AETHER_EXPORT
char *aether_inference_generate(struct AetherInferenceEngine *engine,
                                const char *prompt);
#endif

#if !defined(__wasm32__)
/**
 * 一次性生成完整文本，返回拼接后的字符串。
 * 调用方需用 `aether_free_string` 释放返回值。失败返回空指针。
 * # Safety
 * `engine` 来自 `aether_inference_new` 且已加载模型；`prompt` 合法 NUL 结尾 UTF-8。
 */
AETHER_EXPORT
char *aether_inference_generate_text(struct AetherInferenceEngine *engine,
                                     const char *prompt);
#endif

#if !defined(__wasm32__)
/**
 * 模型是否已加载。
 * # Safety
 * `engine` 来自 `aether_inference_new`。
 */
AETHER_EXPORT bool aether_inference_is_loaded(const struct AetherInferenceEngine *engine);
#endif

#if !defined(__wasm32__)
/**
 * 卸载模型，释放内存。
 * # Safety
 * `engine` 来自 `aether_inference_new`。
 */
AETHER_EXPORT void aether_inference_unload(struct AetherInferenceEngine *engine);
#endif

#if !defined(__wasm32__)
/**
 * 释放推理引擎。空指针安全。
 * # Safety
 * `engine` 来自 `aether_inference_new`，且只能释放一次。
 */
AETHER_EXPORT void aether_inference_free(struct AetherInferenceEngine *engine);
#endif

#endif  /* AETHER_CORE_FFI_H */
