#!/usr/bin/env python3
import json
from pathlib import Path

# Manual translations for user-facing strings extracted from priority files.
TRANSLATIONS = {
    "AI Builder 致力于保护您的隐私": {"en": "AI Builder is committed to protecting your privacy", "zh-Hant": "AI Builder 致力於保護您的隱私"},
    "AI Builder 隐私政策": {"en": "AI Builder Privacy Policy", "zh-Hant": "AI Builder 隱私政策"},
    "API Key 存储在系统 Keychain,不会离开本设备。": {"en": "API Key is stored in the system Keychain and never leaves this device.", "zh-Hant": "API Key 儲存在系統 Keychain，不會離開本裝置。"},
    "API 与模型": {"en": "API & Model", "zh-Hant": "API 與模型"},
    "API 原始响应": {"en": "API Raw Response", "zh-Hant": "API 原始回應"},
    "API 配置": {"en": "API Configuration", "zh-Hant": "API 配置"},
    "Embedding 维度": {"en": "Embedding Dimension", "zh-Hant": "Embedding 維度"},
    "RAG 启用后会在发送消息前检索本地知识库；工具调用启用后会进入 ReAct 循环。": {"en": "When RAG is enabled, the local knowledge base is queried before sending messages; tool calling enters a ReAct loop.", "zh-Hant": "啟用 RAG 後會在傳送訊息前檢索本地知識庫；啟用工具呼叫後會進入 ReAct 循環。"},
    "SHA256 校验": {"en": "SHA256 Checksum", "zh-Hant": "SHA256 校驗"},
    "【用户偏好】": {"en": "[User Preferences]", "zh-Hant": "【使用者偏好】"},
    "一、数据收集范围": {"en": "1. Data Collection Scope", "zh-Hant": "一、資料收集範圍"},
    "三、用户权利": {"en": "3. User Rights", "zh-Hant": "三、使用者權利"},
    "上次上报时间": {"en": "Last Upload Time", "zh-Hant": "上次上報時間"},
    "上次上报状态": {"en": "Last Upload Status", "zh-Hant": "上次上報狀態"},
    "下载": {"en": "Download", "zh-Hant": "下載"},
    "不支持的模型量化格式，请选择 Q4_K_M 或更轻量版本": {"en": "Unsupported quantization format; please choose Q4_K_M or a lighter version", "zh-Hant": "不支援的模型量化格式，請選擇 Q4_K_M 或更輕量版本"},
    "不适用": {"en": "Not Applicable", "zh-Hant": "不適用"},
    "主供应商失败时自动切换到备用供应商重试一次。": {"en": "Automatically switch to the backup provider once when the primary provider fails.", "zh-Hant": "主供應商失敗時自動切換到備用供應商重試一次。"},
    "主供应商失败时自动切换备用供应商": {"en": "Automatically switch to backup provider when primary fails", "zh-Hant": "主供應商失敗時自動切換備用供應商"},
    "二、第三方 SDK": {"en": "2. Third-Party SDKs", "zh-Hant": "二、第三方 SDK"},
    "产品经理": {"en": "Product Manager", "zh-Hant": "產品經理"},
    "从文件选择 PDF 或文本文档导入知识库": {"en": "Import PDF or text documents into the knowledge base", "zh-Hant": "從檔案選擇 PDF 或文字文件匯入知識庫"},
    "从未": {"en": "Never", "zh-Hant": "從未"},
    "从相册选择图片附加到消息": {"en": "Select an image from the photo library to attach", "zh-Hant": "從相簿選擇圖片附加到訊息"},
    "优质": {"en": "Premium", "zh-Hant": "優質"},
    "会话列表": {"en": "Conversations", "zh-Hant": "對話列表"},
    "你好,我是 AI Builder,很高兴为你服务。": {"en": "Hello, I am AI Builder. Happy to assist you.", "zh-Hant": "你好，我是 AI Builder，很高興為你服務。"},
    "你的智能助手": {"en": "Your intelligent assistant", "zh-Hant": "你的智慧助手"},
    "供应商": {"en": "Provider", "zh-Hant": "供應商"},
    "供应商与降级": {"en": "Provider & Fallback", "zh-Hant": "供應商與降級"},
    "保存 API Key": {"en": "Save API Key", "zh-Hant": "儲存 API Key"},
    "停止录音": {"en": "Stop Recording", "zh-Hant": "停止錄音"},
    "停止试听": {"en": "Stop Preview", "zh-Hant": "停止試聽"},
    "停止语音输入": {"en": "Stop Voice Input", "zh-Hant": "停止語音輸入"},
    "健康": {"en": "Health", "zh-Hant": "健康"},
    "健康上下文": {"en": "Health Context", "zh-Hant": "健康上下文"},
    "健康管理": {"en": "Health Management", "zh-Hant": "健康管理"},
    "健身教练": {"en": "Fitness Coach", "zh-Hant": "健身教練"},
    "全选": {"en": "Select All", "zh-Hant": "全選"},
    "关于": {"en": "About", "zh-Hant": "關於"},
    "写作助手": {"en": "Writing Assistant", "zh-Hant": "寫作助手"},
    "切换模型": {"en": "Switch Model", "zh-Hant": "切換模型"},
    "切换语言后需重启 App 生效。选择「跟随系统」将使用设备系统语言。": {"en": "Restart the app to apply language changes. Choosing Follow System uses the device language.", "zh-Hant": "切換語言後需重啟 App 生效。選擇「跟隨系統」將使用裝置系統語言。"},
    "删除 API Key": {"en": "Delete API Key", "zh-Hant": "刪除 API Key"},
    "删除对话": {"en": "Delete Conversation", "zh-Hant": "刪除對話"},
    "删除本地模型文件以释放空间": {"en": "Delete the local model file to free up space", "zh-Hant": "刪除本地模型檔案以釋放空間"},
    "功能与偏好": {"en": "Features & Preferences", "zh-Hant": "功能與偏好"},
    "功能开关": {"en": "Feature Toggles", "zh-Hant": "功能開關"},
    "发送消息": {"en": "Send Message", "zh-Hant": "發送訊息"},
    "发送消息前检索本地知识库增强上下文": {"en": "Retrieve local knowledge base before sending to enrich context", "zh-Hant": "傳送訊息前檢索本地知識庫增強上下文"},
    "取消下载": {"en": "Cancel Download", "zh-Hant": "取消下載"},
    "取消全选": {"en": "Deselect All", "zh-Hant": "取消全選"},
    "取消置顶": {"en": "Unpin", "zh-Hant": "取消置頂"},
    "否": {"en": "No", "zh-Hant": "否"},
    "启用 BFF 代理": {"en": "Enable BFF Proxy", "zh-Hant": "啟用 BFF 代理"},
    "启用 RAG 知识库": {"en": "Enable RAG Knowledge Base", "zh-Hant": "啟用 RAG 知識庫"},
    "启用后 API Key 由服务端保护，设备只持有 BFF Token。": {"en": "When enabled, the API Key is protected by the server; the device only holds the BFF Token.", "zh-Hant": "啟用後 API Key 由伺服器保護，裝置只持有 BFF Token。"},
    "启用后在断网时使用本地模型推理": {"en": "Enable local model inference when offline", "zh-Hant": "啟用後在斷網時使用本地模型推理"},
    "启用后进入 ReAct 循环调用工具": {"en": "Enable ReAct loop for tool calling", "zh-Hant": "啟用後進入 ReAct 循環呼叫工具"},
    "启用端侧推理": {"en": "Enable On-Device Inference", "zh-Hant": "啟用端側推理"},
    "启用自动降级": {"en": "Enable Auto-Fallback", "zh-Hant": "啟用自動降級"},
    "四、联系方式": {"en": "4. Contact", "zh-Hant": "四、聯繫方式"},
    "回复中": {"en": "Responding", "zh-Hant": "回覆中"},
    "在下方输入消息，或点击右上角设置 API Key": {"en": "Type a message below, or tap the settings button to configure your API Key", "zh-Hant": "在下方輸入訊息，或點擊右上角設定 API Key"},
    "增强": {"en": "Enhanced", "zh-Hant": "增強"},
    "失败": {"en": "Failed", "zh-Hant": "失敗"},
    "好": {"en": "OK", "zh-Hant": "好"},
    "如有任何隐私相关问题，请通过邮件联系：feedback@aibuilder.app": {"en": "For any privacy-related questions, please contact us at feedback@aibuilder.app", "zh-Hant": "如有任何隱私相關問題，請透過郵件聯繫：feedback@aibuilder.app"},
    "如：我是素食者…": {"en": "e.g. I am a vegetarian…", "zh-Hant": "如：我是素食者…"},
    "学习导师": {"en": "Learning Mentor", "zh-Hant": "學習導師"},
    "学生": {"en": "Student", "zh-Hant": "學生"},
    "对话": {"en": "Conversations", "zh-Hant": "對話"},
    "导入 PDF 或文本文档，让 AI 基于你的资料回答": {"en": "Import PDF or text documents so AI can answer based on your materials", "zh-Hant": "匯入 PDF 或文字文件，讓 AI 基於你的資料回答"},
    "导入失败": {"en": "Import Failed", "zh-Hant": "匯入失敗"},
    "展开": {"en": "Expand", "zh-Hant": "展開"},
    "展示最近一次发送的 prompt、API 响应、embedding 维度与工具调用。": {"en": "Displays the most recent prompt, API response, embedding dimension, and tool calls.", "zh-Hant": "展示最近一次傳送的 prompt、API 回應、embedding 維度與工具呼叫。"},
    "工具调用": {"en": "Tool Calls", "zh-Hant": "工具呼叫"},
    "工具调用成功": {"en": "Tool call succeeded", "zh-Hant": "工具呼叫成功"},
    "工具调用流程": {"en": "Tool Call Flow", "zh-Hant": "工具呼叫流程"},
    "已下载": {"en": "Downloaded", "zh-Hant": "已下載"},
    "已完成": {"en": "Completed", "zh-Hant": "已完成"},
    "已授权": {"en": "Authorized", "zh-Hant": "已授權"},
    "已生成洞察": {"en": "Insights Generated", "zh-Hant": "已生成洞察"},
    "已通过": {"en": "Passed", "zh-Hant": "已通過"},
    "开发者": {"en": "Developer", "zh-Hant": "開發者"},
    "开启后发送消息时会注入最近 24 小时的睡眠/心率/步数数据，AI 将给出针对性建议。": {"en": "When enabled, sleep/heart rate/step data from the last 24 hours is injected into messages for targeted advice.", "zh-Hant": "開啟後傳送訊息時會注入最近 24 小時的睡眠/心率/步數資料，AI 將給出針對性建議。"},
    "开始下载端侧推理模型文件": {"en": "Start downloading the on-device inference model", "zh-Hant": "開始下載端側推理模型檔案"},
    "开始录音": {"en": "Start Recording", "zh-Hant": "開始錄音"},
    "开始语音输入": {"en": "Start Voice Input", "zh-Hant": "開始語音輸入"},
    "引用来源": {"en": "Citations", "zh-Hant": "引用來源"},
    "当前会话生效。新建对话沿用此值。": {"en": "Applies to the current conversation. New conversations will use this value.", "zh-Hant": "目前對話生效。新建對話沿用此值。"},
    "当前供应商": {"en": "Current Provider", "zh-Hant": "目前供應商"},
    "当前模型": {"en": "Current Model", "zh-Hant": "目前模型"},
    "当前状态": {"en": "Current Status", "zh-Hant": "目前狀態"},
    "思考中": {"en": "Thinking", "zh-Hant": "思考中"},
    "性能指标": {"en": "Performance Metrics", "zh-Hant": "效能指標"},
    "感谢反馈，我们会持续改进": {"en": "Thanks for your feedback; we will keep improving", "zh-Hant": "感謝回饋，我們會持續改進"},
    "感谢点赞": {"en": "Thanks for the thumbs up", "zh-Hant": "感謝點讚"},
    "打开此会话": {"en": "Open this conversation", "zh-Hant": "打開此對話"},
    "打开知识库管理文档": {"en": "Open knowledge base document management", "zh-Hant": "打開知識庫管理文件"},
    "执行中": {"en": "Running", "zh-Hant": "執行中"},
    "执行中…": {"en": "Running…", "zh-Hant": "執行中…"},
    "批量删除": {"en": "Batch Delete", "zh-Hant": "批次刪除"},
    "技术面试官": {"en": "Technical Interviewer", "zh-Hant": "技術面試官"},
    "投诉反馈": {"en": "Feedback & Complaints", "zh-Hant": "投訴回饋"},
    "折叠": {"en": "Collapse", "zh-Hant": "摺疊"},
    "拉取时间": {"en": "Fetched At", "zh-Hant": "拉取時間"},
    "授权后可读取心率、睡眠、步数等健康数据": {"en": "Authorization allows reading heart rate, sleep, steps, and other health data", "zh-Hant": "授權後可讀取心率、睡眠、步數等健康資料"},
    "授权状态": {"en": "Authorization Status", "zh-Hant": "授權狀態"},
    "接入 HealthKit 后 AI 可基于健康数据给出针对性建议。": {"en": "After connecting HealthKit, AI can give targeted advice based on your health data.", "zh-Hant": "接入 HealthKit 後 AI 可基於健康資料給出針對性建議。"},
    "推理配置": {"en": "Inference Configuration", "zh-Hant": "推理配置"},
    "搜索会话标题…": {"en": "Search conversation titles…", "zh-Hant": "搜尋對話標題…"},
    "断网时自动切换到端侧推理，联网后切回": {"en": "Automatically switch to on-device inference when offline and back when online", "zh-Hant": "斷網時自動切換到端側推理，連網後切回"},
    "断网自动切换": {"en": "Auto-Switch on Network Loss", "zh-Hant": "斷網自動切換"},
    "新对话": {"en": "New Conversation", "zh-Hant": "新建對話"},
    "新标题": {"en": "New Title", "zh-Hant": "新標題"},
    "无": {"en": "None", "zh-Hant": "無"},
    "无工具调用": {"en": "No tool calls", "zh-Hant": "無工具呼叫"},
    "是": {"en": "Yes", "zh-Hant": "是"},
    "暂无性能数据": {"en": "No performance data yet", "zh-Hant": "暫無效能資料"},
    "更新日期：2026年7月": {"en": "Updated: July 2026", "zh-Hant": "更新日期：2026年7月"},
    "最近 Prompt JSON": {"en": "Latest Prompt JSON", "zh-Hant": "最近 Prompt JSON"},
    "未下载": {"en": "Not Downloaded", "zh-Hant": "未下載"},
    "未发送": {"en": "Not Sent", "zh-Hant": "未發送"},
    "未拉取": {"en": "Not Fetched", "zh-Hant": "未拉取"},
    "未授权": {"en": "Not Authorized", "zh-Hant": "未授權"},
    "未知": {"en": "Unknown", "zh-Hant": "未知"},
    "未配置": {"en": "Not Configured", "zh-Hant": "未配置"},
    "本地路径": {"en": "Local Path", "zh-Hant": "本機路徑"},
    "查看 AI Builder 隐私政策": {"en": "View AI Builder Privacy Policy", "zh-Hant": "查看 AI Builder 隱私政策"},
    "查看详情": {"en": "View Details", "zh-Hant": "查看詳情"},
    "查看调试信息": {"en": "View Debug Info", "zh-Hant": "查看除錯資訊"},
    "标准": {"en": "Compact", "zh-Hant": "標準"},
    "标记此回复为无帮助": {"en": "Mark this response as unhelpful", "zh-Hant": "標記此回覆為無幫助"},
    "标记此回复为有帮助": {"en": "Mark this response as helpful", "zh-Hant": "標記此回覆為有幫助"},
    "模型名": {"en": "Model Name", "zh-Hant": "模型名稱"},
    "模型已就绪，约 700MB": {"en": "Model ready, ~700MB", "zh-Hant": "模型就緒，約 700MB"},
    "模型文件约 700MB，建议在 Wi-Fi 下下载": {"en": "Model file is ~700MB; download over Wi-Fi is recommended", "zh-Hant": "模型檔案約 700MB，建議在 Wi-Fi 下下載"},
    "正式": {"en": "Formal", "zh-Hant": "正式"},
    "每天 09:00 自动生成一次，也可手动触发。": {"en": "Automatically generated daily at 09:00; can also be triggered manually.", "zh-Hant": "每天 09:00 自動產生一次，也可手動觸發。"},
    "注入健康上下文": {"en": "Inject Health Context", "zh-Hant": "注入健康上下文"},
    "洞察": {"en": "Insights", "zh-Hant": "洞察"},
    "洞察已生成": {"en": "Insight generated", "zh-Hant": "洞察已生成"},
    "消息输入框": {"en": "Message Input", "zh-Hant": "訊息輸入框"},
    "清除性能指标": {"en": "Clear Performance Metrics", "zh-Hant": "清除效能指標"},
    "清除搜索": {"en": "Clear Search", "zh-Hant": "清除搜尋"},
    "点击右上角加号开始第一段对话": {"en": "Tap the plus button to start your first conversation", "zh-Hant": "點擊右上角加號開始第一段對話"},
    "版本": {"en": "Version", "zh-Hant": "版本"},
    "生成中...": {"en": "Generating…", "zh-Hant": "生成中…"},
    "用当前音色朗读示例句": {"en": "Read the sample sentence with the current voice", "zh-Hant": "用目前音色朗讀示例句"},
    "白领": {"en": "Office Professional", "zh-Hant": "白領"},
    "知识库为空": {"en": "Knowledge base is empty", "zh-Hant": "知識庫為空"},
    "确定": {"en": "Confirm", "zh-Hant": "確定"},
    "确定删除此对话？删除后无法恢复。": {"en": "Delete this conversation? This action cannot be undone.", "zh-Hant": "確定刪除此對話？刪除後無法恢復。"},
    "立即上报": {"en": "Upload Now", "zh-Hant": "立即上報"},
    "立即生成洞察": {"en": "Generate Insight Now", "zh-Hant": "立即生成洞察"},
    "端侧推理在断网时自动启用，模型文件约 700MB。": {"en": "On-device inference auto-enables when offline; model file is ~700MB.", "zh-Hant": "端側推理在斷網時自動啟用，模型檔案約 700MB。"},
    "端侧推理无需 API Key，模型在本地运行。": {"en": "On-device inference does not require an API Key; the model runs locally.", "zh-Hant": "端側推理無需 API Key，模型在本地運行。"},
    "端侧模型管理": {"en": "On-Device Model Management", "zh-Hant": "端側模型管理"},
    "管理": {"en": "Management", "zh-Hant": "管理"},
    "管理端侧模型": {"en": "Manage On-Device Models", "zh-Hant": "管理端側模型"},
    "管理者": {"en": "Manager", "zh-Hant": "管理者"},
    "系统默认": {"en": "System Default", "zh-Hant": "系統預設"},
    "索引中…": {"en": "Indexing…", "zh-Hant": "索引中…"},
    "维护模式": {"en": "Maintenance Mode", "zh-Hant": "維護模式"},
    "缓冲事件数": {"en": "Buffered Events", "zh-Hant": "緩衝事件數"},
    "编辑": {"en": "Edit", "zh-Hant": "編輯"},
    "置顶": {"en": "Pin to Top", "zh-Hant": "置頂"},
    "翻译官": {"en": "Translator", "zh-Hant": "翻譯官"},
    "自动": {"en": "Auto", "zh-Hant": "自動"},
    "自动降级": {"en": "Auto-Fallback", "zh-Hant": "自動降級"},
    "触发降级": {"en": "Fallback Triggered", "zh-Hant": "觸發降級"},
    "设备可用内存不足，端侧推理需要至少 4GB 可用内存": {"en": "Insufficient available memory; on-device inference requires at least 4GB free", "zh-Hant": "裝置可用記憶體不足，端側推理需要至少 4GB 可用記憶體"},
    "试听示例": {"en": "Preview Sample", "zh-Hant": "試聽示例"},
    "语气": {"en": "Tone", "zh-Hant": "語氣"},
    "请先在设置中配置 API Key": {"en": "Please configure your API Key in Settings first", "zh-Hant": "請先在設定中配置 API Key"},
    "请求 HealthKit 授权": {"en": "Request HealthKit Authorization", "zh-Hant": "請求 HealthKit 授權"},
    "请求授权": {"en": "Request Authorization", "zh-Hant": "請求授權"},
    "调试信息": {"en": "Debug Info", "zh-Hant": "除錯資訊"},
    "调试面板": {"en": "Debug Panel", "zh-Hant": "除錯面板"},
    "赞": {"en": "Helpful", "zh-Hant": "讚"},
    "跳转系统设置": {"en": "Open System Settings", "zh-Hant": "跳轉系統設定"},
    "踩": {"en": "Not Helpful", "zh-Hant": "踩"},
    "轻松": {"en": "Casual", "zh-Hant": "輕鬆"},
    "输入消息…": {"en": "Type a message…", "zh-Hant": "輸入訊息…"},
    "输入要发送的消息": {"en": "Enter a message to send", "zh-Hant": "輸入要傳送的訊息"},
    "还没有对话": {"en": "No conversations yet", "zh-Hant": "還沒有對話"},
    "这些偏好会被注入到系统提示词，影响 AI 回复风格与工具选择。": {"en": "These preferences are injected into the system prompt and affect AI reply style and tool selection.", "zh-Hant": "這些偏好會被注入到系統提示詞，影響 AI 回覆風格與工具選擇。"},
    "远程配置 / 遥测": {"en": "Remote Config / Telemetry", "zh-Hant": "遠端配置 / 遙測"},
    "选「自动」时由智能路由根据消息特征决定；选具体模型时禁用智能路由。": {"en": "Auto lets the smart router decide based on message features; choosing a specific model disables smart routing.", "zh-Hant": "選「自動」時由智慧路由根據訊息特徵決定；選具體模型時停用智慧路由。"},
    "选中模型": {"en": "Selected Model", "zh-Hant": "選中模型"},
    "选择 App 界面语言，切换后需重启 App 生效": {"en": "Choose the app interface language; restart the app to apply", "zh-Hant": "選擇 App 介面語言，切換後需重啟 App 生效"},
    "选择 LLM 供应商": {"en": "Choose an LLM provider", "zh-Hant": "選擇 LLM 供應商"},
    "选择 LLM 供应商。不同供应商的 API Key 独立存储。": {"en": "Choose an LLM provider. API Keys for different providers are stored separately.", "zh-Hant": "選擇 LLM 供應商。不同供應商的 API Key 獨立儲存。"},
    "选择一个分类": {"en": "Choose a category", "zh-Hant": "選擇一個分類"},
    "选择一个文档": {"en": "Choose a document", "zh-Hant": "選擇一個文件"},
    "选择图片": {"en": "Choose Image", "zh-Hant": "選擇圖片"},
    "选择朗读音色、语速、音调与音量。增强/优质音色首次使用时系统会自动下载。": {"en": "Choose voice, rate, pitch, and volume. Enhanced/premium voices are auto-downloaded on first use.", "zh-Hant": "選擇朗讀音色、語速、音調與音量。增強/優質音色首次使用時系統會自動下載。"},
    "选择模型": {"en": "Choose Model", "zh-Hant": "選擇模型"},
    "选择系统内置 TTS 音色": {"en": "Choose a built-in TTS voice", "zh-Hant": "選擇系統內建 TTS 音色"},
    "选择角色": {"en": "Choose Role", "zh-Hant": "選擇角色"},
    "选自动时智能路由，选具体模型则固定使用": {"en": "Auto uses smart routing; a specific model is fixed", "zh-Hant": "選自動時智慧路由，選具體模型則固定使用"},
    "通义千问 Qwen": {"en": "Tongyi Qwen", "zh-Hant": "通義千問 Qwen"},
    "通过邮件反馈问题或投诉": {"en": "Send feedback or complaints via email", "zh-Hant": "透過郵件回饋問題或投訴"},
    "配置版本": {"en": "Config Version", "zh-Hant": "配置版本"},
    "重命名": {"en": "Rename", "zh-Hant": "重新命名"},
    "重命名对话": {"en": "Rename Conversation", "zh-Hant": "重新命名對話"},
    "重新拉取配置": {"en": "Refetch Config", "zh-Hant": "重新拉取配置"},
    "需下载": {"en": "Download Required", "zh-Hant": "需下載"},
    "需要语音识别权限": {"en": "Speech recognition permission required", "zh-Hant": "需要語音識別權限"},
    "预设角色": {"en": "Preset Role", "zh-Hant": "預設角色"},
    "默认": {"en": "Default", "zh-Hant": "預設"},
    "默认供应商": {"en": "Default Provider", "zh-Hant": "預設供應商"},
    "默认助手": {"en": "Default Assistant", "zh-Hant": "預設助手"},
}

REMOVE_KEYS = {
    "你是一个有帮助的AI助手。",
    "你是健康助手，根据用户的健康数据给出具体可行的建议。",
}

# Additional strings that were not captured (multi-line or interpolated) but are user-facing.
ADDITIONAL = {
    # Privacy policy body paragraphs
    "1. 对话内容：包括用户输入的文本与 AI 生成的回复，用于上下文连续对话与缓存命中加速。": {
        "en": "1. Conversation content: includes text you enter and AI-generated replies, used for continuous context and cache acceleration.",
        "zh-Hant": "1. 對話內容：包括用戶輸入的文字與 AI 生成的回覆，用於上下文連續對話與快取命中加速。"
    },
    "2. 健康数据：包括心率、睡眠时长、步数等，仅在用户明确授权 HealthKit 后读取，用于生成个性化健康洞察。": {
        "en": "2. Health data: includes heart rate, sleep duration, steps, etc., read only after you explicitly authorize HealthKit, used to generate personalized health insights.",
        "zh-Hant": "2. 健康資料：包括心率、睡眠時長、步數等，僅在用戶明確授權 HealthKit 後讀取，用於生成個人化健康洞察。"
    },
    "3. 使用统计：包括性能埋点（如请求延迟、token 数）与崩溃日志，用于持续优化 App 体验。": {
        "en": "3. Usage statistics: includes performance metrics (e.g. request latency, token count) and crash logs, used to continuously improve the app experience.",
        "zh-Hant": "3. 使用統計：包括效能埋點（如請求延遲、token 數）與崩潰紀錄，用於持續最佳化 App 體驗。"
    },
    "1. DeepSeek API：用于对话生成，用户输入文本会上传至 DeepSeek 服务端处理。": {
        "en": "1. DeepSeek API: used for chat generation; text you enter is uploaded to DeepSeek servers for processing.",
        "zh-Hant": "1. DeepSeek API：用於對話生成，用戶輸入文字會上傳至 DeepSeek 伺服器處理。"
    },
    "2. 阿里云百炼 Qwen API：用于对话生成，用户输入文本会上传至阿里云服务端处理。": {
        "en": "2. Alibaba Cloud Bailian Qwen API: used for chat generation; text you enter is uploaded to Alibaba Cloud servers for processing.",
        "zh-Hant": "2. 阿里雲百鍊 Qwen API：用於對話生成，用戶輸入文字會上傳至阿里雲伺服器處理。"
    },
    "3. Bugly：用于崩溃监控，仅上报崩溃堆栈与匿名设备信息，不包含用户对话内容与个人身份信息。": {
        "en": "3. Bugly: used for crash monitoring; only crash stacks and anonymous device info are reported, not conversation content or personal identity information.",
        "zh-Hant": "3. Bugly：用於崩潰監控，僅上報崩潰堆疊與匿名裝置資訊，不包含用戶對話內容與個人身份資訊。"
    },
    "1. 查看已收集数据：可在「设置 - 调试面板」查看最近的请求与响应。": {
        "en": "1. View collected data: recent requests and responses can be viewed in Settings - Debug Panel.",
        "zh-Hant": "1. 查看已收集資料：可在「設定 - 除錯面板」查看最近的請求與回應。"
    },
    "2. 删除对话记录：可在会话列表中删除任意对话，相关数据会从本地数据库移除。": {
        "en": "2. Delete conversation records: any conversation can be deleted from the conversation list; related data is removed from the local database.",
        "zh-Hant": "2. 刪除對話紀錄：可在對話列表中刪除任意對話，相關資料會從本地資料庫移除。"
    },
    "3. 撤回 HealthKit 授权：可在「系统设置 - 隐私 - 健康」中撤回对 AI Builder 的授权。": {
        "en": "3. Revoke HealthKit authorization: you can revoke AI Builder's authorization in System Settings - Privacy - Health.",
        "zh-Hant": "3. 撤回 HealthKit 授權：可在「系統設定 - 隱私 - 健康」中撤回對 AI Builder 的授權。"
    },
    "4. 关闭遥测上报：可在「设置 - 调试面板 - 立即上报」控制上报行为，本地缓冲不强制上报。": {
        "en": "4. Disable telemetry upload: upload behavior can be controlled in Settings - Debug Panel - Upload Now; local buffering does not force uploads.",
        "zh-Hant": "4. 關閉遙測上報：可在「設定 - 除錯面板 - 立即上報」控制上報行為，本地緩衝不強制上報。"
    },
    # OnDeviceError interpolated descriptions (base forms)
    "模型文件未找到：%@": {"en": "Model file not found: %@", "zh-Hant": "模型檔案未找到：%@"},
    "模型文件校验失败（SHA256 不匹配），请重新下载\n期望：%@…\n实际：%@…": {
        "en": "Model file verification failed (SHA256 mismatch). Please re-download.\nExpected: %@…\nActual: %@…",
        "zh-Hant": "模型檔案校驗失敗（SHA256 不匹配），請重新下載\n期望：%@…\n實際：%@…"
    },
    "端侧模型加载失败：%@": {"en": "On-device model failed to load: %@", "zh-Hant": "端側模型載入失敗：%@"},
    # ViewModel dynamic messages
    "无法读取文档内容：%@": {"en": "Unable to read document content: %@", "zh-Hant": "無法讀取文件內容：%@"},
    "导入失败：%@": {"en": "Import failed: %@", "zh-Hant": "匯入失敗：%@"},
    "%@ API Key 已保存": {"en": "%@ API Key saved", "zh-Hant": "%@ API Key 已儲存"},
    "保存失败：%@": {"en": "Save failed: %@", "zh-Hant": "儲存失敗：%@"},
    "%@ API Key 已删除": {"en": "%@ API Key deleted", "zh-Hant": "%@ API Key 已刪除"},
    "授权失败：%@": {"en": "Authorization failed: %@", "zh-Hant": "授權失敗：%@"},
    "生成失败：%@": {"en": "Generation failed: %@", "zh-Hant": "生成失敗：%@"},
    "确定删除选中的 %d 个对话？删除后无法恢复。": {"en": "Delete the selected %d conversations? This action cannot be undone.", "zh-Hant": "確定刪除選中的 %d 個對話？刪除後無法恢復。"},
    "删除选中(%d)": {"en": "Delete Selected (%d)", "zh-Hant": "刪除選中(%d)"},
    "第 %d 轮": {"en": "Round %d", "zh-Hant": "第 %d 輪"},
    "片段 %d": {"en": "Snippet %d", "zh-Hant": "片段 %d"},
    "%d 个片段": {"en": "%d snippets", "zh-Hant": "%d 個片段"},
    "权重 %.1f": {"en": "Weight %.1f", "zh-Hant": "權重 %.1f"},
    "下载中…%d%%": {"en": "Downloading…%d%%", "zh-Hant": "下載中…%d%%"},
    "%d 维": {"en": "%d dimensions", "zh-Hant": "%d 維"},
    "chat 限流（每分钟）：%d": {"en": "Chat rate limit (per minute): %d", "zh-Hant": "chat 限流（每分鐘）：%d"},
    "embed 限流（每分钟）：%d": {"en": "Embed rate limit (per minute): %d", "zh-Hant": "embed 限流（每分鐘）：%d"},
    "maxTokens：%d": {"en": "maxTokens: %d", "zh-Hant": "maxTokens：%d"},
    "语速：%d%%": {"en": "Rate: %d%%", "zh-Hant": "語速：%d%%"},
    "音量：%d%%": {"en": "Volume: %d%%", "zh-Hant": "音量：%d%%"},
}

def main():
    src = Path('scripts/priority_strings.json')
    data = json.loads(src.read_text(encoding='utf-8'))
    out = []
    for item in data:
        key = item['key']
        if key in REMOVE_KEYS:
            continue
        trans = TRANSLATIONS.get(key, {})
        out.append({
            'key': key,
            'zh-Hans': key,
            'zh-Hant': trans.get('zh-Hant', ''),
            'en': trans.get('en', ''),
        })
    for key, trans in ADDITIONAL.items():
        out.append({
            'key': key,
            'zh-Hans': key,
            'zh-Hant': trans.get('zh-Hant', ''),
            'en': trans.get('en', ''),
        })
    out_path = Path('scripts/new_strings.json')
    out_path.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding='utf-8')
    print(f'Wrote {len(out)} translated strings -> {out_path}')

if __name__ == '__main__':
    main()
